### ISSUE TITLE
ELK stack을 활용한 데이터 log 수집 및 시각화

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#100]
# elastic stack

![image](https://github.com/jms0522/Medical-project/assets/132258503/25c9a414-d3d3-4fef-9800-4869c6a387bc)

## 계획

1. airflow가 크롤링을 해서 db에 저장하기 전에 csv 파일을 떨군다.
2. csv의 생성 혹은 변화를 Filebeat가 탐지해 logstash에게 보낸다
3. elastic search에 logstash가 기록을 보냄 (여기서 필요한 컬럼만 전처리 가능)
4. kibana, grafana를 이용한 시각화 가능

## 최종적으로 모든 container 연동 및 container 상태 시각화에 목적

**Comment by jms0522** [comment]
# elastic page

## drrc:5601

![스크린샷 2024-03-10 05 15 32](https://github.com/jms0522/Medical-project/assets/132258503/ecd83e44-d7ba-45b9-8cd5-a3ccf1e83a4e)

**Comment by jms0522** [comment]
# EC2 elk 구축

## 데이터 넣기 전 인덱스 생성해서 넣어야 함 (dev tool 이용)
## 크롤링 데이터 추가 시, 각각의 config를 만들어서 각각의 Index 넣어서 만들 예정

<img width="1052" alt="스크린샷 2024-03-11 17 17 53" src="https://github.com/jms0522/Medical-project/assets/132258503/eb510200-5f80-4340-8289-eb48f4fbdbb2">



<img width="1702" alt="스크린샷 2024-03-11 17 18 02" src="https://github.com/jms0522/Medical-project/assets/132258503/81558f4f-ef33-4c91-8eff-c39b65c9223b">



<img width="842" alt="스크린샷 2024-03-11 17 18 29" src="https://github.com/jms0522/Medical-project/assets/132258503/cb70fe27-7c2e-4335-abd9-eb782be1ac97">




<img width="1073" alt="스크린샷 2024-03-11 17 19 48" src="https://github.com/jms0522/Medical-project/assets/132258503/749a7d8c-49e0-493d-9699-3963cdd18279">



<img width="1074" alt="스크린샷 2024-03-11 17 35 58" src="https://github.com/jms0522/Medical-project/assets/132258503/461ba99b-5c9b-4f4f-a9cd-4b0b6d697b5a">




<img width="853" alt="스크린샷 2024-03-11 17 43 29" src="https://github.com/jms0522/Medical-project/assets/132258503/0b00e774-a2dc-486e-9c3a-d69646ffdfdd">

**Comment by jms0522** [comment]
# hidak

## index 

<img width="623" alt="스크린샷 2024-03-13 10 18 51" src="https://github.com/jms0522/Medical-project/assets/132258503/755387d9-fed9-4b3c-98a9-17919ba920f2">

- 제목, 질문과 답변은 text 형식으로 검색이나, 분석에 유리하게 생성함 (사용자의 자유형식 질문에 유리)
- 병원, 의사이름은 keyword 타입으로 집계나 정렬, 필터링을 하기 위해 생성
- 날짜는 시계열 데이터

**Comment by jms0522** [comment]
# hidak data visualization on kibana

## csv 자체가 RAG 용으로 제작한 csv를 사용해 컬럼값이 좀 이상함
## csv를 다시 생성하거나,  json filter를 사용해서 가져와도 될 듯..


<img width="1696" alt="스크린샷 2024-03-13 11 57 18" src="https://github.com/jms0522/Medical-project/assets/132258503/d3ba1d68-88bc-42af-a1a6-66d823818b71">


### 원래 있던 naver dashboard에 추가함

<img width="1702" alt="스크린샷 2024-03-13 12 20 16" src="https://github.com/jms0522/Medical-project/assets/132258503/3010df5c-7513-4390-bd02-a92b12281ea8">

**Comment by stfano** [comment]
<img width="686" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/90c833f0-18bd-4dee-bac4-61b5fa9134b1">


<img width="697" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/344f5eab-a1f6-45a3-83d6-8f395f2653dc">

**Comment by jms0522** [comment]
# 네이버 QnA total data

##  네이버 토탈 데이터를 전처리 하고 전국 병원 정보의 데이터와 합쳐서 elasticsearch에 업로드

[병원정보서비스](https://github.com/jms0522/Medical-project/files/14617595/1.xlsx)

## 위치 표시를 위한 위도 , 경도를 추가하고 병원코드 및 시도 코드를 추가함
## 소속이나 병원 이름도 답변에서 추출해서 컬럼 생성

![스크린샷 2024-03-16 00 34 24](https://github.com/jms0522/Medical-project/assets/132258503/87a42d35-db20-4ad0-af96-d8e6cd31ef1f)

- 220만개
- text는 간단하게만 전처리

**Comment by jms0522** [comment]
# elasticsearch upload

## 문제 1
- 위도 경도가 geo point로 잘 변환이 안된다.

## 해결

- docs를 보니까 해결 됨 / 양식에 문제가 있었던 듯

![스크린샷 2024-03-16 00 36 25](https://github.com/jms0522/Medical-project/assets/132258503/b23b90e9-e188-4aa1-b23a-49f74446a41c)

## 문제 2 인덱스 설정 문제

- naver_index로 한번 실패한 뒤 fix_naver_index로 바꿔서 올렸는데 실패
- Logstash 권한 문제로 해결

<img width="1396" alt="index_role권한목록" src="https://github.com/jms0522/Medical-project/assets/132258503/5372c957-78dd-4d9f-b485-fc02f02acc2e">


## 문제 3 docs count

- logstash에서 데이터는 계속 올라감
![data upload logstash](https://github.com/jms0522/Medical-project/assets/132258503/2ee59997-30d7-4736-88c8-f3a0ac290b03)

- elastic search에선 doc count가 올라가지 않는다

![total_naver_index](https://github.com/jms0522/Medical-project/assets/132258503/919570fd-feaf-4e56-a3b9-ff957a6b5e36)

## 해결을 위해 시도 해 볼만 한 것

- 샤드와 레플리카 수를 조정한다 (index 생성 시)
- elasticsearch 힙 메모리를 늘린다 256 -> 512 (이건 해놓음)
- 데이터를 파싱하는데 문제가 있을 수 있어서 text 형식의 컬럼을 좀 더 전처리함 (해놓음)

내일 다시 시도..

**Comment by jms0522** [comment]
# 네이버 QnA logstash 

## 220만개를 한번에 넣는 게 문제가 있다고 판단.
## 테스트 용도로  랜덤으로 5만개를 잘라서 logstash input

---

# geo point로 넣을 때 주의사항

## 1. dev tool에서 index를 만들 때 geo point로 맵핑을 해줘야한다

<img width="1636" alt="스크린샷 2024-03-16 18 27 38" src="https://github.com/jms0522/Medical-project/assets/132258503/4fbc446b-3f23-429e-9c05-6c8ddb791f7b">


## 2. csv 자체 즉, 컬럼의 타입을 date는 date로 lot, lon은 float 타입으로 변경해서 넣어줘야 문제가 안 생김. (0으로 표시되는 현상)
## 3. csv filter에서 mutate 할 때 rename말고 add_field를 사용함

<img width="581" alt="스크린샷 2024-03-16 19 06 09" src="https://github.com/jms0522/Medical-project/assets/132258503/0a0477ff-7f04-4067-90da-f1fe8c0a4916">

## 4. 도커 내에서 사용하는 network를 잘 확인해야함 (connection refuesd 오류)

## 5. input 컬럼엔 순서가 중요하고 date를 앞에 넣는 걸 추천


# ✅ 결과물 

-모든 데이터가 아닌 건 참고 바람


<img width="1035" alt="스크린샷 2024-03-16 19 12 09" src="https://github.com/jms0522/Medical-project/assets/132258503/157b348e-df4a-48db-8f68-75ede80a5057">


<img width="220" alt="스크린샷 2024-03-16 19 12 34" src="https://github.com/jms0522/Medical-project/assets/132258503/9cd5eac2-7660-40b1-be2e-200bafb70f00">


<img width="220" alt="스크린샷 2024-03-16 19 12 47" src="https://github.com/jms0522/Medical-project/assets/132258503/dfb4c0ba-a315-4811-b75d-400e9d7b02e9">

<img width="220" alt="스크린샷 2024-03-16 19 13 01" src="https://github.com/jms0522/Medical-project/assets/132258503/19125ed8-4e8b-446d-a1f5-d6675c236144">

**Comment by jms0522** [comment]
# 해결 해야 하는 상황

## docs 문제 csv 행의 수 잘못 자른듯요..

**Comment by jms0522** [comment]
# 해결 과제

- 아마 반영이 느렸던 듯 오늘 다시 compose up 해서 보니 , 3만개 넘게 들어가 있었다.
- 5만개 넣는데도 이렇게 오래 걸린다고 생각하면 220만개 넣을 수 있을까 라는 생각이 듬.
- 배치를 통해 넣거나 elastic agent를 더 생성해서 분산처리 해야 하나 고민 중

![Uploading 스크린샷 2024-03-17 16.11.19.png…]()

**Comment by jms0522** [comment]
# naver 5만개 완료

- data 타입을 dev tool애서 맵핑 할 때  formatd을
- ### "format": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" 이런식으로 넣어야함.


## 결과물

<img width="1000" alt="스크린샷 2024-03-17 17 03 18" src="https://github.com/jms0522/Medical-project/assets/132258503/21e1c422-4242-4f5d-8bad-3c19a8ee880d">


<img width="1000" alt="스크린샷 2024-03-17 17 05 06" src="https://github.com/jms0522/Medical-project/assets/132258503/9d512364-e0af-497b-9c15-bf56e776b56f">

**Comment by jms0522** [comment]
# 네이버 전처리 데이터 220만개 완료

## sincedb_path를 설정하지 않아서 데이터가 더 들어가는 듯하다.
<img width="1070" alt="스크린샷 2024-03-17 21 19 00" src="https://github.com/jms0522/Medical-project/assets/132258503/ee1a015c-134c-4a24-9b4e-1040798320a2">

## 간단한 분석 대시보드 완성

<img width="1692" alt="스크린샷 2024-03-17 21 20 36" src="https://github.com/jms0522/Medical-project/assets/132258503/688e1ec3-20bd-41e5-acb2-ec869649a06b">


## 📌 해결과제 
- sincedb_path를 설정해 데이터가 중복으로 들어가지 않도록 설정해야함

**Comment by jms0522** [comment]
# hidoc 페이지 구성 완료

## 하이닥 전처리 후 18만개 데이터

<img width="1059" alt="스크린샷 2024-03-17 21 23 00" src="https://github.com/jms0522/Medical-project/assets/132258503/d824c819-deb9-43d6-8801-6a612f8f1cba">



![스크린샷 2024-03-17 22 52 29](https://github.com/jms0522/Medical-project/assets/132258503/3ab03ef5-baa1-4815-8d55-b7ce3c5752a9)

**Comment by jms0522** [comment]
# 업데이트 대시보드 구현 

## 네이버 
## 하이닥
## 닥터나우 

## airflow를 통해 생성되는 csv를 읽어서 업데이트 해주는 update dashboard 구현 완료

<img width="953" alt="스크린샷 2024-03-19 16 32 29" src="https://github.com/jms0522/Medical-project/assets/132258503/33351fb0-9aa6-4a6c-833f-487fda35d4b3">


# 전체 구현한 elasticsearch dashboard list

<img width="919" alt="스크린샷 2024-03-19 16 33 38" src="https://github.com/jms0522/Medical-project/assets/132258503/3b1732e2-7e7b-4821-b08e-217afc58b002">

**Comment by jms0522** [comment]
# sincedb_path 문제 해결

##  각 인덱스 별로 파일을 만들어 추적, 관리 한다.

<img width="548" alt="sincedb_path" src="https://github.com/jms0522/Medical-project/assets/132258503/515a8fe6-41ad-4e11-82f2-cc345937f3a9">

## naver_total_sincedb_file

- 읽은 부분까지 적혀져 있는 걸 볼 수 있음. (잘 작동함)

<img width="803" alt="naver update sincedb 내용" src="https://github.com/jms0522/Medical-project/assets/132258503/f675be3c-6148-48fb-a646-008a1e0f9152">
