### ISSUE TITLE
Amazon EventBridge & Lamda를 통한 EC2 Instance 스케쥴링

### ISSUE THREAD

**Issue by cheol2Y** [jms0522/Medical-project#107]
# EC2 instance의 on/off 를 스케쥴링에 대하여..

**Comment by cheol2Y** [comment]
Lambda에서 Python 함수를 만들고, 이것을 정해진 시간에 실행 시키기 위하여
Amazon EventBridge를 사용한다.

이것을 사용한 이유는 하루에 한번씩 데이터를 수집하는 airflow Instance를 항상 켜둘 필요가 없기 때문이다.
특정 시간에만 Instance가 켜지고 작업이 완료되면 자동으로 종료되게 하는 것을 구현하기 위해서이다.

**Comment by cheol2Y** [comment]
# Lambda
![image](https://github.com/jms0522/Medical-project/assets/113869397/692dac84-7cb5-41b8-8a2a-48f64b9ace76)
- Lambda에서 함수 생성을 클릭하여 필요한 함수를 생성한다.
- 사용할 언어와 아키텍처를 선택한다.
- 동작시킬 함수를 작성하고 deploy를 한 후 test를 하여 코드가 정상적으로 작동하는 지를 확인한다.

**Comment by cheol2Y** [comment]
# Amazon EventBridge
![image](https://github.com/jms0522/Medical-project/assets/113869397/728e588f-3c9e-4e0e-b979-51c71ea21cd7)
- 특정 시간에 Lamda 함수를 실행 시키기 위하여 EventBridge를 사용한다.
- 매일 반복 되게끔 일정을 생성할 것이기 때문에 Cron 양식을 사용하여 매일 실행되게 설정한다.
- 실행할 Lambda를 선택한다.

![image](https://github.com/jms0522/Medical-project/assets/113869397/fb2ddbbb-90df-41b1-9c91-dfb8c454b47e)

**Comment by cheol2Y** [comment]
# IAM 권한
- 현재 인스턴스를 키고 끄는 권한이 필요하기 때문에 Lambda에게 해당 권한을 주어야한다.
- AmazonEC2FullAccess를 Lambda에게 부여한다.

**Comment by jms0522** [comment]
good
