### ISSUE TITLE
네이버지식인 페이지 100제한으로 의사 답변 정보를 이용한 크롤링

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#15]
전문가 페이지로 들어가서 크롤링하자는 의견
페이지 제한 없음
의사 프로필 링크 크롤링 > 질문 링크 크롤링 >  질문답변 크롤링 순서로 크롤링

**Comment by minseok1994** [comment]
naver_bydoctor.ipynb 파일을 통해 크롤링 중.
시간이 오래걸리기는 하나 가능할듯!

**Comment by cheol2Y** [comment]
코드 최적화가 필요할듯함
제 개인 컴퓨터 기준 doc_id를 가져오는 과정은 1.2초정도가 소요되고
qna data를 가져오는데는 0.7초가 걸림

**Comment by jms0522** [comment]
> 코드 최적화가 필요할듯함 제 개인 컴퓨터 기준 doc_id를 가져오는 과정은 1.2초정도가 소요되고 qna data를 가져오는데는 0.7초가 걸림

화긴화긴~

**Comment by jms0522** [comment]
![image (1)](https://github.com/jms0522/Medical-project/assets/132258503/ff0260ae-dc9e-4e6c-8222-3e1903eff2b7)
- EC2를 이용해 크롤링

**Comment by jms0522** [comment]
![image (2)](https://github.com/jms0522/Medical-project/assets/132258503/3821f727-6c22-40a5-b3f0-cd11aad53459)
- 결과
