### ISSUE TITLE
naver question and answer crawling 

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#4]
네이버 크롤링 시 일정 이상 크롤링을 진행하면 네이버에서 ip를 막아버리는 현상

-> random 함수를 사용하여 간격의 텀을 두어 시도

**Comment by cheol2Y** [comment]
https://kin.naver.com/qna/detail.naver?d1id=7&dirId=70101&docId=463854562
현재 docId를 찾는 방법이 없었다.

**Comment by cheol2Y** [comment]
selenium을 사용하면 쉽게 해결할 수 있는 문제이지만 시간이 많이 소요된다는 단점이 존재했다.

**Comment by cheol2Y** [comment]
https://kin.naver.com/qna/expertAnswerList.naver?dirId=70101
카테고리(dirId)별로 페이지를 돌아가면서 docId를 추출하였다.

**Comment by cheol2Y** [comment]
최종적으로 크롤링을 하는 과정은 3개의 부분으로 정리되었다.
dirId를 얻는 부분
dirId를 통해서 docId를 얻는 부분
docId를 통해서 question과 answer 데이터를 가져오는 부분

**Comment by cheol2Y** [comment]
크롤링을 매일 일정한 시간에 한다고 한다면,
DB에 저장된 데이터가 어디에서 부터인지 구분할만한 식별 데이터가 있어야 할것으로 보인다.
이것을 어떻게 해결할 것인가?

**Comment by cheol2Y** [comment]
저장은 dirId별로 json 파일로 저장할 예정

**Comment by jms0522** [comment]
완료되면 issue 닫아주면 milestones 진행률 올라감
