### ISSUE TITLE
⚒️ Model turning (Prompt, Retriever, Vector Store   etc..)

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#41]
-우리의 서비스와 가장 알맞은 프롬포트 찾기 혹은 생성하기
[https://smith.langchain.com/hub?organizationId=0d055bfd-13a8-5d54-8120-6fb395759bea](LangSmith)

#59

**Comment by jms0522** [comment]
![](https://files.slack.com/files-pri/T05M51ACQGK-F06KBR4SE5Q/image.png)
- gemini를 이용한 RAG 모델 결과 도출
- 확실히 좋은 성능을 보인다. 
- LLM 모델을 finetune해서 사용하기로 했지만, 리소스도 많이 들고 성능이 더 높다는 보장이 없다
- RAG 방식을 통한 결과 도출은 정답인 듯..

**Comment by jms0522** [comment]
- 모두의 ai 조언

![image](https://github.com/jms0522/Medical-project/assets/132258503/b10c1ce6-fbc3-456c-b627-def5d96333c6)

**Comment by jms0522** [comment]
# 0219 retriever turning 

리트리버를 튜닝하는 방법은 다양합니다. 몇 가지 튜닝 방법은 다음과 같습니다:

검색 유형 변경: search_type 매개변수를 수정하여 다른 검색 유형을 시도할 수 있습니다. 예를 들어, "bm25"나 "dpr"과 같은 다른 검색 유형을 사용해 보세요.

추가 검색 매개변수 설정: search_kwargs 매개변수를 사용하여 추가 검색 매개변수를 설정할 수 있습니다. 예를 들어, k 매개변수를 조정하여 검색 결과의 수를 변경하거나, fetch_k 매개변수를 조정하여 각 검색 결과의 상위 문서 수를 변경할 수 있습니다.

외부 데이터 추가: 검색 성능을 향상시키기 위해 외부 데이터를 추가할 수 있습니다. 이는 리트리버의 성능을 개선하는 데 도움이 될 수 있습니다.

모델 파라미터 조정: 리트리버를 생성하는 데 사용된 모델의 파라미터를 조정하여 성능을 향상시킬 수 있습니다. 이는 모델을 다시 훈련하거나 미세 조정하는 등의 작업을 포함할 수 있습니다.

전처리 및 후처리: 검색된 문서의 전처리나 후처리를 추가하여 검색 결과를 개선할 수 있습니다. 이는 텍스트 정규화, 토큰화, 불용어 제거 등의 작업을 포함할 수 있습니다.

**Comment by jms0522** [comment]
# lang smith 
## embedding : jhgan/ko-sroberta-multitask
## model : gemini-pro
![Uploading 스크린샷 2024-02-19 12.48.44.png…]()

**Comment by jms0522** [comment]
# Vector store 비교
https://discuss.pytorch.kr/t/2023-picking-a-vector-database-a-comparison-and-guide-for-2023/2625

**Comment by jms0522** [comment]
# Prompt 변경에 따른 답변의 변화

<img width="1307" alt="스크린샷 2024-02-19 14 54 45" src="https://github.com/jms0522/Medical-project/assets/132258503/d9540752-7cee-49b8-b03c-b3311ff4721a">

- prompt 튜닝을 통해 답변 정제를 할 수 있을 듯.

**Comment by jms0522** [comment]
# prompt tune

<img width="1392" alt="스크린샷 2024-02-20 15 25 06" src="https://github.com/jms0522/Medical-project/assets/132258503/614cf44c-d667-4152-ada4-88090c50ca72">

**Comment by stfano** [comment]
# chunk_size 에 따른 답변 변화

##  chunksize : 2000
<img width="631" alt="스크린샷 2024-02-20 오후 5 38 42" src="https://github.com/jms0522/Medical-project/assets/57385696/8bfbb954-256b-4369-a1a7-b9e2163beff1">


## chunksize : 500
![Uploading 스크린샷 2024-02-20 오후 5.47.09.png…]()

**Comment by jms0522** [comment]
reopen issue

**Comment by stfano** [comment]
# 03/04

<img width="602" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/40a97dc1-8964-46bb-8e0d-328d61e52788">

<img width="598" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/91a5f921-7126-4d92-8aa9-37192a394d4b">

<img width="609" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/440664ca-2ffa-43b1-b02e-e2fa45576af8">

**Comment by stfano** [comment]
prompt

<img width="455" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/f746cbd8-753e-4f8a-973d-48cf8206bc31">

**Comment by jms0522** [comment]
## chunk size = 1000 와 over lap = 50 , 컬럼 하나의 text로 전처리

<img width="1040" alt="스크린샷 2024-03-04 19 30 45" src="https://github.com/jms0522/Medical-project/assets/132258503/f0108a2e-5801-4d73-b64d-c54ffe9e7b61">

**Comment by jms0522** [comment]
# 0305 prompt tuning 을 통한 챗봇 성능 향상

### 질문은 실제 네이버 지식인 질문을 가져와 사용.

## 첫 번째 시도

<img width="1039" alt="스크린샷 2024-03-05 10 15 58" src="https://github.com/jms0522/Medical-project/assets/132258503/20c15cc0-4965-4c76-83b9-b1d1ad34b6d3">

## 두 번째 시도

<img width="1047" alt="스크린샷 2024-03-05 10 22 02" src="https://github.com/jms0522/Medical-project/assets/132258503/1304d615-3af5-49dd-845f-667c500dc1a9">

##  prompt 튜닝을 통해 문맥을 이해하고 vectort db를 참고해 답변을 잘 하는 것을 확인

**Comment by jms0522** [comment]
# Graph db

## 하나의 병명에 치료, 증상, 원인 등으로 관계를 가지고 묶이고 있고
## 공통으로 들어가는 인자로 병명끼리도 묶이고 있음
## 답변의 정확도가 향상 될 거라 생각함.

- limit 1500
<img width="1142" alt="스크린샷 2024-03-05 12 34 09" src="https://github.com/jms0522/Medical-project/assets/132258503/d05ba0d5-5d86-4af8-aa1f-0d62fc31dcc6">

- 확대
<img width="1242" alt="스크린샷 2024-03-05 12 34 22" src="https://github.com/jms0522/Medical-project/assets/132258503/a059b9bc-48ba-4456-a94e-e1cba6abbe5a">

**Comment by jms0522** [comment]
# Neoj4 를 벡터화 결과값

## 그래프 db 후에 벡터화 ( chroma retriever ) 위의 답변
## 원래 ensemble retriever와 text 형식으로 전치리 했을 때 결과값

<img width="1029" alt="스크린샷 2024-03-05 16 17 14" src="https://github.com/jms0522/Medical-project/assets/132258503/64ce13db-75e8-42e7-b9c5-e953ff15f65a">

# Neoj4 벡터화 후 모델 답변 (네이버 지식인 실제 데이터 활용)

<img width="1034" alt="스크린샷 2024-03-05 16 18 28" src="https://github.com/jms0522/Medical-project/assets/132258503/e8275253-5876-44f0-96a2-f1119cde116a">

**Comment by jms0522** [comment]
# 약 추가하기 ( 그래프 확장 후 벡터화)

## 1. 약 정보 전처리 

<img width="1384" alt="스크린샷 2024-03-06 12 43 18" src="https://github.com/jms0522/Medical-project/assets/132258503/ceba3233-625d-4ea1-a0fb-4eb175b42fdb">

- [ ] 전처리 완료

## 2. 약 정보 Disease 그래프와 treat로 관계를 맺어 벡터 db화 진행

- disease 와 medicine 사이 관계를 맺어주어 참고가 가능하게 했음 (외래키 개념)

<img width="1520" alt="스크린샷 2024-03-06 12 42 37" src="https://github.com/jms0522/Medical-project/assets/132258503/9a19f3e1-978e-4c6c-9841-6395662560eb">

- [ ] 관계 맺기, 벡터 db화 완료.


## 결과값 확인

<img width="1057" alt="스크린샷 2024-03-06 12 42 04" src="https://github.com/jms0522/Medical-project/assets/132258503/1da8c6cc-c077-433e-b109-4ab543169dae">

**Comment by jms0522** [comment]
# medicine graph 

- 결과값을 확인해보니, medicine 의 연결 관계가 제대로 포함되지 않았다고 판단
- 두개의 메인 node를 생성한 뒤 연결관계를 같이 벡터화 하는 쿼리를 수정하여 다시 시도

<img width="1651" alt="스크린샷 2024-03-07 09 13 23" src="https://github.com/jms0522/Medical-project/assets/132258503/a636a69e-fa4e-4af5-95e8-3af0b602db20">

- 새롭게 정의된 그래프
- 질병과 약에 대한 관계가 treats, has medicine으로 정의 했고,
- 약의 세부 정보는 약의 속성으로 포함되고 있다고 생각하면 될 듯.
-

**Comment by jms0522** [comment]
# 0307 결과값 비교

<img width="704" alt="스크린샷 2024-03-07 09 34 41" src="https://github.com/jms0522/Medical-project/assets/132258503/e10e2098-1d13-4069-b3ae-90860af1a4e1">

<img width="1041" alt="스크린샷 2024-03-07 09 34 50" src="https://github.com/jms0522/Medical-project/assets/132258503/3a4d537a-1ee4-44ea-a31a-10a71f8dbf34">


<img width="696" alt="스크린샷 2024-03-07 09 35 21" src="https://github.com/jms0522/Medical-project/assets/132258503/065315cb-ddbf-4714-9999-9fcecddb6bb8">

<img width="1042" alt="스크린샷 2024-03-07 09 36 50" src="https://github.com/jms0522/Medical-project/assets/132258503/fa903ffa-22e2-424a-a0d3-ac74553c5bfa">
