### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#55]
# 의료 데이터를 구하기 위한 방법 (생각 단계)

##  음성 데이터 - 텍스트 데이터 변환으로 데이터 수집
https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=566
- 주제별 텍스트 대화 데이터에서 의료, 건강만 추출

- 음성 데이터는 많이 존재해서 음성을 텍스트로 변환해서 데이터셋을 가져오는 방법도 고려해 볼 수 있음.
- 의료 데이터는 어떤 데이터든 오프라인 안심존에 가서만 사용이 가능함 [사용 불가 ❌](https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=566)

**Comment by jms0522** [comment]
# preview

## 데이터 전처리 전
<img width="1306" alt="스크린샷 2024-02-22 09 16 56" src="https://github.com/jms0522/Medical-project/assets/132258503/cb1a6776-6ff0-44af-a357-49ff97682e98">

## 데이터 전처리 후
<img width="1294" alt="스크린샷 2024-02-22 09 16 16" src="https://github.com/jms0522/Medical-project/assets/132258503/55bfde45-9a01-4548-8923-5e396595f6e9">
@stfano  @cheol2Y  @minseok1994

**Comment by jms0522** [comment]
# 전처리 과정

1. 결측치 제거 또는 채우기
데이터셋 내의 질문(question)이나 답변(answer)에 결측치가 있는 경우, 해당 행을 제거하거나 적절한 값으로 채워야 합니다.
2. 텍스트 정규화
텍스트의 일관성을 높이기 위해 소문자화, 대문자화 또는 다른 형태의 정규화를 수행할 수 있습니다.
불필요한 공백, 탭, 줄바꿈 등을 제거하여 텍스트를 깔끔하게 정리합니다.
3. 구두점 및 특수 문자 처리
마침표(.), 물음표(?), 쉼표(,) 등과 같은 구두점의 처리는 질문의 종류를 구분하거나 문장의 경계를 인식하는 데 도움이 될 수 있습니다.
필요에 따라 특수 문자를 제거하거나 특정 기호를 유지합니다.
4. 불용어 제거
일반적으로 의미 있는 정보를 제공하지 않는 불용어(stop words)를 제거하여 모델의 학습에 집중할 수 있는 중요한 정보만 남깁니다.
5. 토큰화
텍스트를 단어, 구, 문장 등으로 나누는 토큰화 과정을 통해 모델이 처리하기 쉬운 형태로 데이터를 변환합니다.
6. 어간 추출(Stemming) 또는 표제어 추출(Lemmatization)
단어의 기본 형태를 추출하여 모델이 다양한 변형된 형태의 단어를 같은 단어로 인식할 수 있도록 합니다.
7. 엔티티 인식 및 이름 대체
특정 이름, 위치, 기관 등의 엔티티를 인식하고, 이를 일반화된 태그나 다른 표현으로 대체하여 데이터의 일반화 능력을 높일 수 있습니다.
8. 데이터 증강
질문의 다양성을 높이기 위해 동의어 교체, 문장 재구성 등의 방법으로 데이터를 증강할 수 있습니다.
9. 문장 길이 조정
너무 긴 문장을 분할하거나, 특정 길이 이상의 문장을 잘라내어 모델의 입력 크기를 표준화합니다.
이러한 전처리 단계들은 모델의 목적과 특성, 그리고 사용할 데이터의 특성에 따라 선택적으로 적용될 수 있습니다. 가장 중요한 것은 전처리 과정이 최종 모델의 성능에 긍정적인 영향을 미쳐야 한다는 것입니다.

**Comment by jms0522** [comment]
# 0222 total naver QnA 
- 전처리 과정에 사용한 stopword list : [https://www.ranks.nl/stopwords/korean](url)
- 사용한 형태소 분석기 : konlpy

**Comment by stfano** [comment]
### 0224 

## hidak processing 
- 하나의 답변이 아닌 여러개의 답변도 존재하기에 리스트인 답변을 모두 하나의 텍스트로 합침
- 안녕하세요 ~ 00의사입니다. 라는 텍스트 삭제
- 게시글이 삭제된 질문은 모두 삭제

# 전처리 전 데이터 양 
<img width="860" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/53658cf6-a16d-4a68-a66e-522edee5e79c">


# 전처리 후 데이터 양 
<img width="1032" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/2499974b-2e30-4d6e-af7d-1a983480ee74">

- 확정된 전처리 방식이 아니기에 로컬에만 저장해둠
