### ISSUE TITLE
📌 RAG / LLM Fine tuning

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#57]
1. LoRA / Fine tuning 

- Fine tuning 
- 이미 훈련된 모델에  새로운 정보를 추가하는 것이 아니라, 모델의 행동을 변경. 특정 Response를 보장할 수 있다.

2. RAG
- 이미 훈련된 LLM 모델에 외부 데이터를 참조하여 답을 생성.
- 실제로 새로운 사실을 추가하는 게 아니라 요청에 사용된 프롬포트에 관련 정보를 제공.

- RAG의 한계
- 무분별한 정보 검색 때문에 신뢰할 수 있는 정보인지에 대해 판단하는 능력 부족 (검증 불가)
- 특정 분야나 상황에 최적화된 정보를 제공하기 어려워 일반적인 정보만 제공할 가능성이 높음.

3. Fine tuning & RAG의 차이점

- Fine tuning은 모델의 행동을 조정하거나 특화 시키는 데 중점을 둔다. 

- RAG는 외부 데이터 소스를 검색하여 모델에 추가 정보를 제공한다. 지식을 추가하지 않고 검색 결과를 활용한다.

**Comment by jms0522** [comment]
의료 빅데이터를 활용한 인공지능 문진 및 스마트 진료지원 시스템 구축 : https://www.bics.re.kr/governRnd/subject/read/subject/36891
RAG를 이용한 한국어 오픈 도메인 질의 응답 : https://nlp.jbnu.ac.kr/papers/hclt2022_RAG_ODQA.pdf

**Comment by stfano** [comment]
# 메모리 부족 문제

구글 코랩에서 제공하는 gpu 서버 t4, k-ict 빅데이터센터에서 받은 gpu, mac안에 내장에 있는 gpu 모두 써보았지만 csv 6000행 하나 finetuning 하는데 메모리 부족현상 발생 , epoch, batch size 을 줄여보았지만 마지막 trian 과정에서 메모리 부족 문제

## macos gpu 메모리 부족 
<img width="951" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/580b367e-01ee-4b19-8ae9-c6bdcaf19b09">

## k-ict 빅데이터 센터 gpu 메모리 부족

<img width="1375" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/dfeb8bcf-5ee3-4d4e-8d46-9e35b88b9393">

## 구글 코렙 t4 서버 메모리 부족 

<img width="736" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/cd42b0d7-a03d-4134-8a8d-92dac714bf62">

**Comment by jms0522** [comment]
# 허깅페이스 데이터셋 업로드


<img width="1016" alt="스크린샷 2024-02-22 11 55 21" src="https://github.com/jms0522/Medical-project/assets/132258503/5e66d40d-92b9-4e26-ae4e-8a2189164be8">

**Comment by stfano** [comment]
# huggingface 리더보드 상위 모델 결과 비교해보기

## 02/25

**공통 질문 : b형 간염 보균자인데 아르기닌 먹어도되나요?**

### 리더보드 1등 모델 : Edentns/DataVortexS-10.7B-dpo-v1.11

![image](https://github.com/jms0522/Medical-project/assets/57385696/d8e73de9-061b-4cdb-afdc-ec97af47b833)


### 리더보드 2등 모델 : LDCC/LDCC-SOLAR-10.7B

![image](https://github.com/jms0522/Medical-project/assets/57385696/885b8b58-9626-48e5-8ff8-56a60d90a117)

### 의료지식 학습된 모델 : squarelike/llama2-ko-medical-7b

![image](https://github.com/jms0522/Medical-project/assets/57385696/f0a3df06-19a4-4da4-8e70-19fa1aae8eea)

### 리더보드 11등 모델  : megastudyedu/M-SOLAR-10.7B-v1.3-dpo
![image](https://github.com/jms0522/Medical-project/assets/57385696/eb8268af-e482-4efa-b5cd-a995145e603f)


### 결국 gemini
<img width="756" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/671a84e6-c1f4-4095-be9c-fae805b7ff88">


- 미친 성능의 gemini
