### ISSUE TITLE
RAG model Retriever tuning

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#59]
# 진행 과정을 올리는 issue page

날짜 / 변경사항 / 결과 캡쳐

**Comment by jms0522** [comment]
# 2020 retriever : Ensemble Retriever
<img width="1416" alt="스크린샷 2024-02-20 12 50 47" src="https://github.com/jms0522/Medical-project/assets/132258503/e62bc4f4-7d18-4028-bd70-fae626c923fe">

**Comment by jms0522** [comment]
# 병명 5개 도출하기
<img width="1396" alt="스크린샷 2024-02-20 16 24 43" src="https://github.com/jms0522/Medical-project/assets/132258503/4f586591-e5f2-4707-a21e-249952fcfbaf">

**Comment by stfano** [comment]
# MultiQueryRetriever
<img width="751" alt="스크린샷 2024-02-21 오후 11 57 56" src="https://github.com/jms0522/Medical-project/assets/57385696/5d301d84-b17d-4398-869a-4c207c1648bc">


- **MultiQueryRetriever**
    - 거리 기반 벡터 데이터베이스 검색은 쿼리를 고차원 공간에 내장시키고 “거리”를 기반으로 유사한 내장 문서를 찾는다.
    - 사용자 입력 쿼리에 대해 다양한 관점에서 여러 쿼리를 생성하는 LLM을 사용

**Comment by stfano** [comment]
# Ensemble Retriever
<img width="721" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/6f8b3fe6-9901-4731-9907-b9d2ea75392d">


- **EnsembleRetriever**
    - 가장 일반적인 패턴은 키워드기반 리트리버 (예 : BM25)와 조밀 한 리트리버 (예 : 유사성 포함)를 결합하는 것이다.
    - 앙상블할 가중치를 통해 얼마나 유사한 문서인지 찾아낸다.


✅ **정리**

여러가지 retriever를 써봤는데 답변이 매우 비슷하게 나온것을 확인했다. 아무래도 데이터의 양이 적기 때문이 아닐까 라는 개인적인 생각이 들었다.
