### ISSUE TITLE
🧑🏻‍💻 Web 

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#64]
**민석님은 web 작업 하실 때 기능별 버전별 브랜치 생성해서 해주세요**

ex) drrc_login_ver1

**ex) commit message: "type: fix title: 변경 사항 요약"

# design 

# preview

**Comment by minseok1994** [comment]
![image](https://github.com/jms0522/Medical-project/assets/145941741/f44abcbb-80ad-4543-99ad-e16402332689)
next.js로 chatbot제작한 소스코드를 활용하여 구축해볼 예정.
잘 되면 api 수정하고, html수정하여 완성.
잘 안되면 기존대로 장고 + 리액트로 전환

**Comment by jms0522** [comment]
> ![image](https://private-user-images.githubusercontent.com/145941741/307270791-f44abcbb-80ad-4543-99ad-e16402332689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDAzMjcsIm5iZiI6MTcwODcwMDAyNywicGF0aCI6Ii8xNDU5NDE3NDEvMzA3MjcwNzkxLWY0NGFiY2JiLTgwYWQtNDU0My05OWFkLWUxNjQwMjMzMjY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxNDUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODU5NTk1YmNhNjMzOWRhYjhiZmY4ZDNhZDE4YmNmMWQzM2VmNzhjYzE0YWM1Y2UyN2M3MWRkYWY3NjkwNDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kcp7BpS07b-GNpwaq2hbfyoZ3zbrKGrMVaE2fCOLO_w) next.js로 chatbot제작한 소스코드를 활용하여 구축해볼 예정. 잘 되면 api 수정하고, html수정하여 완성. 잘 안되면 기존대로 장고 + 리액트로 전환

어떤식으로 구상할건지 자세히 써주세요

**Comment by jms0522** [comment]
안 떨린다구요~

**Comment by jms0522** [comment]
# 제대로 된 데이터로 제작한 chroma가 아닌, RAG model chatbot model test

- ver.1.0.0

![스크린샷 2024-02-28 16 54 40](https://github.com/jms0522/Medical-project/assets/132258503/c4222281-204e-4ebf-8d4b-f6b7d36f48fd)

**Comment by minseok1994** [comment]
![image](https://github.com/jms0522/Medical-project/assets/145941741/f7edb349-71ba-4df8-8195-8b9b26efe3b0)

raw data: 서울대학교병원 의학정보
columns = ['병명', '정의', '원인', '증상']
text_splitter = CharacterTextSplitter(chunk_size=600, chunk_overlap=20)
embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
chroma_retriever = chroma_vectorstore.as_retriever(search_kwargs={"k": 5})
bm25_retriever.k = 5
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, chroma_retriever], weights=[0.7, 0.3])
prompt = hub.pull("rlm/rag-prompt")
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

**Comment by minseok1994** [comment]
# postgresql과 장고 연결
- ver.1.1.0
### 사용자 인터랙션 로깅 시스템 구축
<img width="809" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/f7885edc-cbca-4eb8-974c-880f36de635a">
### 챗봇 서비스 데이터 저장 로직 구현
<img width="809" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/1144ab76-1e1c-4827-8c8e-3b3aa0c45724">

**Comment by minseok1994** [comment]
# 로그인, 로그아웃 기능 추가
- ver.1.2.0
### 로그인, 로그아웃 기능
<img width="692" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/6b051c6e-ecef-4c86-a20c-ca4ec96c77f9">

### 로그인 시, 사용자의 대화내역을 불러와 화면에 출력하는 기능 추가
![image](https://github.com/jms0522/Medical-project/assets/145941741/81833752-9ddd-4421-b955-a58b5df33c67)

**Comment by minseok1994** [comment]
# 보안 오류 수정
- ver.1.2.1
### dotenv사용
개발용으로 사용했던 뷰 파일에서 openai_api_key를 노출한 채로 깃허브에 푸시하였음.
<img width="467" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/80367317-7486-40f0-8355-f3260a8f8b03">

푸시하자마자 openai, github에서 유출에 대한 메일이 옴
![image](https://github.com/jms0522/Medical-project/assets/145941741/c89baa8f-0f61-4ceb-adba-761845cdec03)

이를 개선하기 위해 dotenv 모듈을 활용해 .env로 api key를 관리하도록함
![image](https://github.com/jms0522/Medical-project/assets/145941741/24b0e9e8-9a6e-462d-8e41-016d195d71cc)

**Comment by jms0522** [comment]
# 0304 전처리 후 테스트

<img width="1041" alt="스크린샷 2024-03-04 17 52 38" src="https://github.com/jms0522/Medical-project/assets/132258503/d5fadb9e-0cac-4562-8654-4a1f9f3fa2ab">

<img width="1053" alt="스크린샷 2024-03-04 17 54 52" src="https://github.com/jms0522/Medical-project/assets/132258503/c6dd3312-a01d-4901-aed5-34326fdd5576">

- 프롬프트 수정이랑, 청크 수정을 하고 나서 또 확인해보자

**Comment by jms0522** [comment]
## chunk size = 1000 와 over lap = 50 , 컬럼 하나의 text로 전처리

<img width="1040" alt="스크린샷 2024-03-04 19 30 45" src="https://github.com/jms0522/Medical-project/assets/132258503/f0108a2e-5801-4d73-b64d-c54ffe9e7b61">

**Comment by jms0522** [comment]
## 질문에 병명이 들어가 있을 경우 확실히 더 수준 높은 대답을 하는 걸 알 수 있음.

<img width="1682" alt="스크린샷 2024-03-04 19 38 11" src="https://github.com/jms0522/Medical-project/assets/132258503/23e6567e-1924-4b4c-b9f4-2f59e2ce81b7">

**Comment by jms0522** [comment]
# 답변 퀄리티가 왔다 갔다함. 프롬포트 수정 필요함 (프롬포트 튜닝 제로)

<img width="1690" alt="스크린샷 2024-03-04 20 02 47" src="https://github.com/jms0522/Medical-project/assets/132258503/3ef1a84d-22b6-4465-b36c-193c4818d66d">

- 실제 답변

<img width="814" alt="스크린샷 2024-03-04 20 02 58" src="https://github.com/jms0522/Medical-project/assets/132258503/eb3178a1-7ce0-4af0-8668-8fc50b375c94">

**Comment by jms0522** [comment]
# 0305 prompt tuning 을 통한 챗봇 성능 향상

### 질문은 실제 네이버 지식인 질문을 가져와 사용.

## 첫 번째 시도

<img width="1039" alt="스크린샷 2024-03-05 10 15 58" src="https://github.com/jms0522/Medical-project/assets/132258503/20c15cc0-4965-4c76-83b9-b1d1ad34b6d3">

## 두 번째 시도

<img width="1047" alt="스크린샷 2024-03-05 10 22 02" src="https://github.com/jms0522/Medical-project/assets/132258503/1304d615-3af5-49dd-845f-667c500dc1a9">

##  prompt 튜닝을 통해 문맥을 이해하고 vectort db를 참고해 답변을 잘 하는 것을 확인

**Comment by jms0522** [comment]
# Neo4j 활용해 db 구축

- 지식백과 데이터는 컬럼들이 연관성을 가지고 있기 때문에 그래프 형식으로 묶어서 벡터 db를 만들 예정.
- 병명에 대한 원인, 증상, 치료 등이 그래프 형식으로 지정되어 정확성이나 속도 향상이 있을거라 예상.

## NAVER DIEASE

<img width="1079" alt="스크린샷 2024-03-05 10 29 36" src="https://github.com/jms0522/Medical-project/assets/132258503/c1c37bc0-9ed2-42cb-ab87-88e5be26c56c">

**Comment by minseok1994** [comment]
# 유사답변 서비스 생성

- ChromaDB(server)가 완성되지 않아 기존 랭체인llm 모델로 생성
- 추후 랭체인 모델 변경하여 api 수정 필요

![image](https://github.com/jms0522/Medical-project/assets/145941741/80840e9d-035f-4885-a9b8-5fa6cfedf402)

**Comment by minseok1994** [comment]
# 도커 컴포즈 파일구성

- 같은 networks를 사용하도록 구성
- 컨테이너 간의 의존성 설정
- 장고 application의 경우 Dorkerfile 따로 구성

<img width="351" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/f786bd1c-e7bf-4227-a684-d839a7794f7f">

<img width="851" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/8b29256a-93db-4a55-bbf7-7e432975d6ec">

**Comment by minseok1994** [comment]
# html, css 업데이트 및 코드 리팩토링

- 챗봇 페이지 외에 병원/약국 찾기, 백과사전 페이지 추가
![image](https://github.com/jms0522/Medical-project/assets/145941741/62ed5932-b507-4b76-b3e5-21e688aa264d)

<img width="1390" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/1a4ef101-c549-48fe-b434-9ef02d81e07d">


<img width="1390" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/4715b12c-5c99-4b6d-a7d2-b4b17b4ca55c">

**Comment by minseok1994** [comment]
# 로그인 페이지 재구성 및 카카오 api로그인 구현
<img width="880" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/bb2f7055-c10a-4fbb-ba9f-0e0a98e4c49b">

<img width="880" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/7ba0ccc8-5333-467c-82e1-96accb94c541">

<img width="880" alt="image" src="https://github.com/jms0522/Medical-project/assets/145941741/d74bc1bc-b8b9-4c66-a015-8efaf7f02e1a">

**Comment by minseok1994** [comment]
# 시각화를 위한 메트릭 기능별로 추가

- urls.py에 path('metrics/', metrics, name='metrics')를 추가하여 프로메테우스로 보냄
- grafana에서 프로메테우스의 자료를 기반으로 시각화(아래)

![image](https://github.com/jms0522/Medical-project/assets/145941741/510e42a4-6b8d-40ec-87f4-4f3218b3fe6e)
