### ISSUE TITLE
데이터 수집 자동화 

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#70]
make workflow and test

**Comment by jms0522** [comment]
# git workflow 을 통해 배포, 배포 전에 테스트를 할 수 있음.
## 그 주제에 대해 공부해오기.

**Comment by jms0522** [comment]
#68 

- 팀원 회의 기록을 보고 전체적인 데이터 파이프라인 구상 개념 확인하기

**Comment by jms0522** [comment]
# 0227 네이버 당일에 의사가 답변을 작성한 QnA 수집 코드 완성

- 당일에 작성한 답변만 가져오게 되어있다. 
- naver_main.py만 실행하면 저장된다.
- 파일 경로는 자신에 맞게 수정할 필요 있음.
- 자동 전처리 코드까지 구축한 뒤 dag로 만들어서 airflow로 실행시킬 예정.

<img width="500" alt="스크린샷 2024-02-27 15 59 13" src="https://github.com/jms0522/Medical-project/assets/132258503/6fbf8ccf-ab39-4465-bc72-051b399b1dba">
- 나는 여기 위치에 저장되고 있고, 마지막 결과 : detail.csv임.

- 수집된 데이터
<img width="1200" alt="스크린샷 2024-02-27 16 00 10" src="https://github.com/jms0522/Medical-project/assets/132258503/81a571e5-e170-4605-acca-973be70b80c8">

- 오늘 날짜만 가져온 doc_id.json

<img width="1200" alt="스크린샷 2024-02-27 16 00 10" src="https://github.com/jms0522/Medical-project/assets/132258503/8a70c894-aa03-4601-8d40-ca1aadb75d4e">

**Comment by jms0522** [comment]
# 0227 닥터나우 실시간 상담 자동 수집 코드 

- realtime_main.py 실행하면 된다.
- 이 데이터도 자동 전처리 과정이 필요하고 그 코드도 추가하여 airflow dag로 만들면 될 듯.

<img width="1287" alt="스크린샷 2024-02-27 16 03 46" src="https://github.com/jms0522/Medical-project/assets/132258503/ca34d667-c857-4c6a-acb4-cac4d1f99e75">

**Comment by jms0522** [comment]
# 0227 네이버, 닥터나우 알림 

- 어디까지 진행되었는지, 데이터 흐름을 알기 쉽게 알림도 설정.

<img width="500" alt="스크린샷 2024-02-27 16 04 58" src="https://github.com/jms0522/Medical-project/assets/132258503/5d27e5d1-6160-48e0-b7e9-2b3d87bc0727">


- 실패의 흔적...

[
<img width="400" alt="스크린샷 2024-02-27 16 05 52" src="https://github.com/jms0522/Medical-project/assets/132258503/85d962d9-ee86-49b2-aa6f-68abb9248fda">

**Comment by stfano** [comment]
# 02/27

## 질문 Link, 질문답변, 전처리 과정 모듈 및 수정 진행

1️⃣ **질문 link**

저장되어있는 모든 질문답변 link json 파일과 과 오늘날짜별로 link 크롤링한 link를 중복없이 비교해서 없는 link 만 따로 json 파일로 저장 
<img width="266" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/ac84636c-ca73-49fe-940b-dbf9860fa453">


2️⃣ **질문답변**

새로운 질문답변 link가 들어오면 json 파일로 저장 ( 원래 csv 파일이였지만 csv파일을 읽을 때 , 로 구분해서 db에 저장된다. 답변이나 질문에서 ,가 많이 쓰이고 제거를 할 수는 없기 때문에 json 으로 저장했다. 
<img width="245" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/8cb06aa2-9ab6-4d49-8c70-99a0c978f4b2">

3️⃣ **전처리**

안녕하세요 누구누구입니다 같은 텍스트나 특수문자 텍스트는 삭제하는 전처리 과정 진행

<img width="244" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/808f438c-420a-4f7e-ba49-a58daa592b60">

**Comment by stfano** [comment]
# 0302

<img width="600" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/7ee9fac9-a406-4b56-8347-b692e8b8ce57">


<img width="608" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/ee7a7241-4b83-4730-b0fe-abd31a2c0153">


<img width="607" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/7aa29af4-e30e-4097-8f86-31186aa389d1">
