### ISSUE TITLE
Airflow dag 생성

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#80]
# 0228 naver qna crawling dag
@cheol2Y  @stfano 

- 아직 db 저장 까지는 구현하지 않음.
![image](https://github.com/jms0522/Medical-project/assets/132258503/5306ab1a-6a8d-4fc1-ab43-ce4715589b0c)

**Comment by stfano** [comment]
<img width="597" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/bf95c831-1174-4f36-b703-7ecf96217ce9">


### db 저장도 연습으로 해봄 
<img width="1268" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/ac2ea548-a1ef-464a-9acb-12fb2aff592a">


- 전처리 자동화 dag는 팀원들과 데이터 값, 칼럼 지정 회의 후 진행 할예정

**Comment by cheol2Y** [comment]
- window 에서 wsl 을 사용하여 docker와 airflow를 사용하게끔 만들었다.
![image](https://github.com/jms0522/Medical-project/assets/113869397/3d91fa07-83d9-415a-a0bc-862df5b72a7b)

- 데이터를 수집까지는 완료했다.
![image](https://github.com/jms0522/Medical-project/assets/113869397/632b5fa4-122a-4f22-b869-e096cbe04bb8)

- 전처리는 간단하게 설계하긴 했으나 추후에 더 강화해야할 필요가 있다.

- PostgreDB에 insert하는 것은 구현은 완료되었다. CLI환경에서 작업하다보니 UI가 좋지는 못하다.

이후에 작업할거
DAG에서 오류발생시 다시 회복할 수 있게끔 구현
전처리 강화

**Comment by cheol2Y** [comment]
docker compose up 할때마다 scheduler container 들어가서 pip install 하는 번거로움이 있음, 이거 해결할 방법 있다면 좋을듯

**Comment by jms0522** [comment]
볼륨을 사용하거나 애초에 필요한 설정 다 한 이미지를 저장하고 그 이미지로 부터 docker compose up 하면 되는거 아녀?
아님 requirement에 적어놓거나

**Comment by jms0522** [comment]
> docker compose up 할때마다 scheduler container 들어가서 pip install 하는 번거로움이 있음, 이거 해결할 방법 있다면 좋을듯

-볼륨을 사용하거나 애초에 필요한 설정 다 한 이미지를 저장하고 그 이미지로 부터 docker compose up 하면 되는거 아녀?
아님 requirement에 적어놓거나

**Comment by cheol2Y** [comment]
- airflow dag 정상 작동
![image](https://github.com/jms0522/Medical-project/assets/113869397/10370f1b-9ae7-4f9b-8c5b-583a4f233262)

- cli 환경에서 postgreDB 조회
![image](https://github.com/jms0522/Medical-project/assets/113869397/c4d45f6d-6138-4eb1-a9a0-08147b57a2ac)

**Comment by cheol2Y** [comment]
PostgresDB 할때 설정할것
리눅스 기준 해당 파일을 수정하면 된다.
1. sudo vim /etc/postgresql/16/main/pg_hba.conf

![image](https://github.com/jms0522/Medical-project/assets/113869397/d4be28af-a458-48de-817d-09c888686e6a)

peer 오류가 뜬다면 md5로 변경
DB에 접속할수 있게끔 권한 줄때 해당 아이피 주소를 입력, 번거롭다면 그냥 전체 ip에 대하여 열어놔도 된다

2. sudo vim /etc/postgresql/16/main/postgresql.conf
ip 접속 권한주기

![image](https://github.com/jms0522/Medical-project/assets/113869397/11242fd7-2a77-4864-ac8b-2fb7ce024de0)

**Comment by stfano** [comment]
<img width="633" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/dabd1e5d-b396-4e08-b8ff-586e9da59243">

**Comment by cheol2Y** [comment]
-docker file 형성
![image](https://github.com/jms0522/Medical-project/assets/113869397/b4204864-a785-4d5e-970d-0d525da658ca)
현재 docker 이미지를 build하고 docker hub에 push하는 작업까지 완료

- 생성한 docker 이미지를 불러와서 docker-compose를 진행
- dag에 코드 최적화 진행중 
- 현재 볼륨을 공유하는 과정에서 권한 오류가 발생해서 문제를 해결하는 중
- DB의 ip 주소만 있으면 생성된 데이터를 바로 연결 할 수 있음

**Comment by cheol2Y** [comment]
- naver data 전처리후 DB에 삽입 성공
![image](https://github.com/jms0522/Medical-project/assets/113869397/16ca8075-f64a-4536-a26a-81852f913dbe)
![image](https://github.com/jms0522/Medical-project/assets/113869397/86c572f4-094d-429d-b508-b53c25395f66)

- hidak data 전처리후 DB에 삽입 성공
![image](https://github.com/jms0522/Medical-project/assets/113869397/3970a672-3490-45bb-8d0d-16d2096cc734)
![image](https://github.com/jms0522/Medical-project/assets/113869397/c1628040-a232-4795-8b84-e979a2f7d221)

postgresql DB의 conf파일을 수정하여 접근 권한을 주어야한다.
ec2의 보안그룹에서도 해당 포트(5432)를 열어주어야 접속이 가능하다.

**Comment by cheol2Y** [comment]
-닥터나우, 하이닥, 네이버 지식인 dag 작성 완료 및 컬럼명 통일

![image](https://github.com/jms0522/Medical-project/assets/113869397/b0ffc6c1-0676-4d3e-b47c-4885dcea7249)
![image](https://github.com/jms0522/Medical-project/assets/113869397/43b0780e-1b46-46e1-85e7-20f36ef1f018)
![image](https://github.com/jms0522/Medical-project/assets/113869397/aa3754a3-2afb-4a82-8849-439264ecd394)


Dag가 실행되면 정보 수집후 정상적으로 DB에 입력된다
