### ISSUE TITLE
📟 추가 Service logics list

### ISSUE THREAD

**Issue by stfano** [jms0522/Medical-project#95]
# 추가 서비스 로직  (03/05 ~ ) 

## 약의 자세한 정보 (복용 방법 , 주의 사항 등등)을 그래프 형식으로 더 엮어서 추가 정보 서비스

**Comment by stfano** [comment]
<img width="666" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/ff8bf932-8a86-4bee-ac74-0e0a2d4a864a">

![image](https://github.com/jms0522/Medical-project/assets/57385696/db201adf-fe30-46a6-a974-49520375ad16)


<img width="363" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/9253cc55-b786-48a3-990b-962483e030c1">

![image](https://github.com/jms0522/Medical-project/assets/57385696/b27074d4-2a67-4d94-a19a-9f337d3c9d81)


<img width="645" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/84a53c6a-9304-4713-a2bf-ef47e7e2c05a">

![image](https://github.com/jms0522/Medical-project/assets/57385696/2ce52ded-bf34-4a3e-8784-bba2473350e5)


<img width="380" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/73a59c5b-84e8-48f4-93c4-017cfa69b651">

![image](https://github.com/jms0522/Medical-project/assets/57385696/8270e03b-a063-4f5b-aa12-d5d603eba028)


- 지금까지는 RecursiveCharacterTextSplitter 의 텍스트 스플리터 기능을 쓰는것이 좋아보인다.

**Comment by jms0522** [comment]
# 추가 서비스 

## 현재 있는 그래프 db에 약의 상세한 정보를 담은 csv를 추가 연동 시켜 정확한 약 정보도 주려고 한다.

<img width="841" alt="스크린샷 2024-03-05 17 39 03" src="https://github.com/jms0522/Medical-project/assets/132258503/b3a00585-09fb-4440-9dff-2a550cf2d588">

**Comment by minseok1994** [comment]
해보자구~

**Comment by stfano** [comment]
<img width="649" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/1fb0e9a9-4404-4661-8ebc-10d4a3b7c20a">


<img width="644" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/eadeee04-26e5-48ad-89b5-b90d5f31dd8e">


### ❗ 이슈

➕ 매일 하루에 한번 들어오는 질문답변 데이터를 vector db 에 저장을 해야하는데 이미 저장된 db를 다시 임베딩하기에는 시간이 부족하고 chroma db 끼리 합치는 방법을 찾아봐야한다. collection.add 를 이용해서 합치는 방법이 존재했지만 임베딩치원이 일치하지 않는다는 이유로 현재 다른방법을 찾고있다.

**Comment by stfano** [comment]
<img width="655" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/3da92f3a-47ab-4f91-827a-c33db852d674">


<img width="657" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/032a0bd8-383f-4562-8ef7-6869de2ad488">

<img width="659" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/74dfb84e-e75b-4459-9d4d-8aef3bb13fcf">

**Comment by stfano** [comment]
# 03/11 ~ 03/12 

- 개이 인스턴스에서 잘 돌아가던 chroma dag 자동화가 서버 인스턴스에서 docker-compose 하면 import error가 자꾸 생겨서 오류가 났다. 
- airflow 버전과 python 버전 그리고 langchain 버전 3개가 모두 호환이 되어야 실행이 되는 조건이였다.
- airflow 에서 task 에 가상환경을 생성한 별도의 모듈을 import 할 수 있는 기능이 있어서 이것을 이용했다.

<img width="605" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/0a201ecc-0b89-4036-956d-2ce509aa8b0e">

- 하지만 어쩔때는 vectordb가 생성이되지만 또 어떨 때는 device 의 용량 부족으로 에러가 난다. 

<img width="605" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/4d93bcdb-99c0-4e9b-b50b-f326c5e8100b">

- 용량은 충분하지만 왜 부족하다고 하지 ??

**Comment by stfano** [comment]
# 03/13 

##  드디어 성공 3일만에 import 오류 해결 

- @task.virtualenv 를 이용해서 dag 전용 가상환경을 세팅 한 후 module를 import 하는 방법을 써보았지만 disk의 용량 부족이라는 오류가 가끔씩 발생해서 처음 방법을 선택했다.
- 가상환경 세팅을 하지않고 scheduler 에서 module를 다시 처음부터 설치를 했다. 
- scheduler python version : 3.11.7
- 가상머신 python version : 3.11.0rc1
- 혹시 몰라서 scheduler 의 requirements.txt 저장 완료 

## Chroma Server Connection
<img width="491" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/3d038a9c-64f1-4aa7-9ae6-8e89b26f438e">
- 원래는 인스턴스에서 localhost를 이용해서 chromadb server에 접속이 가능했지만 airflow로 connection을 하기위해서는 Localhost가 아니라 실제 ip 주소를 적어주어야 chromadb server에 접속이 가능해졌다. 

<img width="492" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/1c84420d-d239-4529-9e3d-df55d1ccf3a7">


##  데이터 확인 

<img width="336" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/4564a8eb-04b7-4e1b-84b1-fc0f4043e528">

<img width="1482" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/6f67a46f-3a83-451f-8888-90844adda4ea">

- 2024년 3월 11일 날짜의 데이터를 참조한 것을 확인 할 수 있다. 
- vectordb 자동화 완료..

##

**Comment by stfano** [comment]
# 03/14

## 닥터나우 데이터도 chormadb에 저장되도록 구현 

<img width="477" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/c9fa026f-4ee6-4b7b-8896-63971ba4a1d7">

- 네이버 csv 폴더, 하이닥 csv 폴더,  닥터나우 csv 폴더 경로에 있는 어제 날짜의 csv폴더를 가져온다.

<img width="1145" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/7cbb3e70-7023-4b95-bf9d-e8eaea6ecf19">

- 3개의 csv 파일을 하나로 합친 후 텍스트를 분할, 임베딩, 저장 하여 collection에 add 한다. 
<img width="578" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/07075dd4-bca2-49b5-9c73-233c017e4922">

**Comment by stfano** [comment]
# 03/15
<img width="657" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/e4394363-1555-4b2c-9057-338eb6ce6f8b">


<img width="656" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/9ef19d12-2a13-457b-be7b-feafa4538e8b">

**Comment by stfano** [comment]
# 03/18

## embedding 모델 수정 

원래 embedding model 이였던 jhgan/ko-sbert-nli 모델을 
jhgan/ko-sroberta-multitask 로 수정하고 vectorDB를 다시 만들었다.
두 모델 모두 한국어 사전학습으로 된 모델이지만 jhgan/ko-sroberta-multitask 모델이 더뛰어난 것을 알게되었다 .


##  embedding model 평가지표 비교

ko-sbert-nli 모델의 평가지표 

<img width="307" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/8c2b689f-5a54-45f6-b32d-fd6d0dff63b6">

ko-sroberta-multitask 모델의 평가지표

<img width="304" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/69be8cc1-4e4a-44a4-a077-9d967668bf1d">


- 큰 차이는 아니지만 모든 지표에서 sroberta 의 지표가 앞선 것을 볼 수 있다. 



### retriever 비교

- 앙상블 리트리버
<img width="549" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/90800ce8-446b-4070-a242-4e69ec5d938c">

<img width="749" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/cd31b8a8-ef3c-4e25-b86c-1d8e902571cc">

- similarity : 질문 벡터와 가장 유사항 문장 벡터를 찾는 방법이 제일 좋은 검색 방법인 것 같다. mmr 같은 방법은 문서들간의 다양성을 최적화 하는 방법이기때문에 잘 맞지 않는다고 판단하였다. 

<img width="735" alt="image" src="https://github.com/jms0522/Medical-project/assets/57385696/5f66ff4e-e15e-46eb-aedd-307847e63777">
